modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/dodogang/plume/issues"
license = "MIT; Assets licensed as All Rights Reserved"

[[mods]]
modId = "plume"
version = "${version}"
displayName = "Plume"
#updateJSONURL = ""
displayURL = "https://github.com/dodogang/plume"
#credits = ""
authors = "Dodo Gang"
description = '''
Dodo Gang Library Mod
'''
#logoFile = ""

[[dependencies.plume]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.plume]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
