modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"
issueTrackerURL = "https://github.com/dodogang/architectury-example-mod/issues"

[[mods]]
modId = "modid"
version = "${version}"
updateJSONURL = ""
displayName = "Example Mod"
#logoFile = ""
#credits = ""
authors = "Dodo Gang"
description = '''
This is an example description! Tell everyone what your mod is about!
'''

[[dependencies.modid]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modid]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"